### ISSUE TITLE
GET /charts/:chartHash is inconsistent with other /charts/ requests

### ISSUE THREAD

**Issue by zkldi** [zkldi/uscir-spec#2]
This is probably intentional, but this returns either 42 or 20, instead of the 42 | 44 | 20 that the other chart endpoints do.

For consistencies sake, the handling of chart-exists/chart-not-found could be moved to the client.

minor gripe and doesn't really matter.

**Comment by ereti** [comment]
This inconsistency is deliberate as the purpose of this endpoint is to check if the server WILL accept a score. As a result, 44 Not Found is never correct. The following situations can occur:

The server knows the chart, and will accept a score - 20.
The server knows the chart, and will not accept a score - 42.
The server does not know the chart, but accepts scores on new charts - 20.
The server does not know the chart, and does not accept scores on new charts - 42.

Contrast this with, for example, GET /charts/:chartHash/record, where the server not knowing of a chart means it cannot possibly provide the server record for it and so 44 Not Found is correct.
