### ISSUE TITLE
GET /charts/:chartHash/leaderboard Ambiguous for N

### ISSUE THREAD

**Issue by zkldi** [zkldi/uscir-spec#4]
If the request has, say, N of 10, but the server only has 5 unique PBs, the specification does not specify what to do explicitly. As it stands, I think the reasonable thing to do is to assume that N is the upper bound for the returned documents, but may be less (incl. 0) for any reason.

**Comment by ereti** [comment]
The documentation for adjacentAbove and adjacentBelow says 0 to N, not N.

**Comment by ereti** [comment]
The specification says n is the limit of scores requested, not the number expected. It is clear that it should be 0 to N.
